const poolABI = [
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"user",
                "type":"address"
            },
            {
                "internalType":"uint32",
                "name":"time",
                "type":"uint32"
            }
        ],
        "name":"getUserBalancesAtTime",
        "outputs":[
            {
                "internalType":"uint",
                "name":"balance0",
                "type":"uint"
            },
            {
                "internalType":"uint",
                "name":"balance1",
                "type":"uint"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"user",
                "type":"address"
            }
        ],
        "name":"getRealTimeUserBalances",
        "outputs":[
            {
                "internalType":"uint",
                "name":"balance0",
                "type":"uint"
            },
            {
                "internalType":"uint",
                "name":"balance1",
                "type":"uint"
            },
            {
                "internalType":"uint256",
                "name":"time",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint32",
                "name":"time",
                "type":"uint32"
            }
        ],
        "name":"getReservesAtTime",
        "outputs":[
            {
                "internalType":"uint112",
                "name":"_reserve0",
                "type":"uint112"
            },
            {
                "internalType":"uint112",
                "name":"_reserve1",
                "type":"uint112"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[],
        "name":"getReserves",
        "outputs":[
            {
                "internalType":"uint112",
                "name":"reserve0",
                "type":"uint112"
            },
            {
                "internalType":"uint112",
                "name":"reserve1",
                "type":"uint112"
            },
            {
                "internalType":"uint32",
                "name":"time",
                "type":"uint32"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[],
        "name":"token0",
        "outputs":[
            {
                "internalType":"contract ISuperToken",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[],
        "name":"token1",
        "outputs":[
            {
                "internalType":"contract ISuperToken",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"contract ISuperToken",
                "name":"_superToken",
                "type":"address"
            }
        ],
        "name":"retrieveFunds",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"returnedBalance",
                "type":"uint256"
            }
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    }
];

export default poolABI;